service: serverlessscraper

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http: 
          path: serverlessscraper/hello
          method: get
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http: 
          path: serverlessscraper/goodbye
          method: post
  getFacilities:
    handler: src/functions/getFacilities.handler
    events:
      - http: 
          path: serverlessscraper/getfacilities
          method: get
    timeout: 120


# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline

# Resources your functions use
# resources:
